### ISSUE TITLE
 `import error` -- when running `run.py`

### ISSUE THREAD

**Issue by nalvid** [spaceexperiment/Code-for-CRUD-admin-tutorial#1]
\app__init__.py", line 14, in <module>
    from admin import admin
ImportError: No module named 'admin'

Win7/Python3/Virtualenv
UPDATE: I changed some imports and now it works ...

**Comment by spaceexperiment** [comment]
what did you change ?

**Comment by nalvid** [comment]
I changed these lines ... I use relative imports: 
in file `app/admin/__init__.py` ...  `from .admin import *`
in file `app/__init__.py` ... `from .admin import admin`
