### ISSUE TITLE
GET based DELETEs are bad practice right?

### ISSUE THREAD

**Issue by rlam3** [spaceexperiment/Code-for-CRUD-admin-tutorial#2]
GET based DELETEs are bad practice right?

https://www.reddit.com/r/flask/comments/2ax1mf/af_delete_example/

Do do you recommend any other way around this?

**Comment by spaceexperiment** [comment]
you are correct. they are bad because the link for delete could be shared and trick user to click on it.

POST or DELETE methods would be best.
